# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- main

pool:
  vmImage: 'ubuntu-22.04'

variables:
  solution: '**/*.sln'
  projects: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildOutputDirectory: '$(Build.ArtifactStagingDirectory)'
  buildRuntime: 'linux-x64'
  buildFramework: 'net8.0'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: 'Restore Project Deps.'
  inputs:
    command: 'restore'
    projects: '$(projects)'
    restoreArguments: '--runtime $(buildRuntime)'
    feedsToUse: 'config'
    nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'

- task: DotNetCoreCLI@2
  displayName: 'Build Projects'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
    projects: '$(projects)'
    arguments: '--no-restore --runtime $(buildRuntime) --configuration $(buildConfiguration) --framework $(buildFramework) --output $(buildOutputDirectory) --self-contained'

# - task: DotNetCoreCLI@2
#   displayName: 'Run Unit Tests'
#   inputs:
#     command: 'test'
#     projects: '$(System.DefaultWorkingDirectory)/tests/**/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: 'Publish Build'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(projects)'
    arguments: '--no-restore --no-build --framework $(buildFramework) --configuration $(buildConfiguration) --runtime $(buildRuntime) --output $(buildOutputDirectory)/publish --self-contained true'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    artifactName: 'Howbot'
    publishLocation: 'Container'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
