# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
name: Howbot Build

trigger:
- main

pool:
  vmImage: 'ubuntu-22.04'

variables:
  solution: '**/*.sln'
  projects: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildOutputDirectory: '$(Build.ArtifactStagingDirectory)/publish'
  buildRuntime: 'ubuntu-22.04-x64'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 7'
  inputs:
    packageType: sdk
    version: '7.x'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  inputs:
    versionSpec: 
    checkLatest: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projects)'
    feedsToUse: 'config'
    nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'
    noCache: true

- task: DotNetCoreCLI@2
  inputs:
    configuration: '$(buildConfiguration)'
    command: 'build'
    projects: '$(projects)'
    arguments: '--output $(buildOutputDirectory) --runtime $(buildRuntime) /p:PublishSingleFile=true /p:SelfContained=true'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'
    msbuildArgs: '/p:SelfContained=true /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(System.DefaultWorkingDirectory)/tests/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish solution'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(projects)'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -r $(buildRuntime) --self-contained true'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    artifactName: 'drop'
    publishLocation: 'Container'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
