# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildOutputDirectory: '$(Build.ArtifactStagingDirectory)/publish'
  buildRuntime: 'linux-x64'
  dotNetVersion: '7.0.100'

steps:
- task: UseDotNet@2
  inputs:
    packageType: runtime
    version: $(dotNetVersion)
- task: NuGetCommand@2
  displayName: 'Nuget Restore'
  inputs:
    restoreSolution: '$(solution)'
    includeNuGetOrg: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    configuration: '$(buildConfiguration)'
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--output $(buildOutputDirectory) --runtime $(buildRuntime) /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true'
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(System.DefaultWorkingDirectory)/tests/**/*.csproj'
- task: CopyFiles@2
  displayName: "Copy Build Files"
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Files as Artifact'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'HowBot'
    publishLocation: 'Container'
